const express = require('express');
const router = express.Router();
const projectController = require('../controller/featureProject.controller');
const verifyAdmin = require('../middleware/auth.middleware');
router.get('/', projectController.getAllProject);
router.get('/:id', projectController.getProjectByID);
router.post('/', verifyAdmin,projectController.createProject);
router.put("/:id", verifyAdmin,projectController.updateProject);
router.delete("/:id",verifyAdmin ,projectController.deleteProject);
module.exports = router;